In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_score, accuracy_score, recall_score


In [3]:
data_sucio = pd.read_csv('DataAnalytics.csv')
data_sucio.head(5)

Administrador  Usuario  botón correcto  tiempo de interacción mini juego  \
0       nicolas  nicolas             1.0               5.399169   Despegue   
1       nicolas  nicolas             0.0               1.283400   Despegue   
2       nicolas  nicolas             1.0               2.700226   Despegue   
3       nicolas  nicolas             0.0               3.050262   Despegue   
4       nicolas  nicolas             0.0               4.750256   Despegue   

   número de interacción color presionado  dificultad  \
0                    1.0             blue  Episodio 1   
1                    2.0           violet  Episodio 1   
2                    3.0            green  Episodio 1   
3                    4.0            green  Episodio 1   
4                    5.0            green  Episodio 1   

                       fecha  Juego  auto push  tiempo de lección  \
0  25/01/2024 09:26:42 a. m.  Astro        0.0                0.0   
1  25/01/2024 09:26:46 a. m.  Astro        0.0                0.0   
2  25/01/2024 09:26:48 a. m.  Astro        0.0                0.0   
3  25/01/2024 09:26:57 a. m.  Astro        0.0                0.0   
4  25/01/2024 09:26:58 a. m.  Astro        0.0                0.0   

   tiempo de sesión  
0               0.0  
1               0.0  
2               0.0  
3               0.0  
4               0.0

In [4]:
data_sucio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5865 entries, 0 to 5864
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Administrador          5865 non-null   object 
 1   Usuario                5865 non-null   object 
 2   botón correcto         5103 non-null   float64
 3   tiempo de interacción  5103 non-null   float64
 4   mini juego             5709 non-null   object 
 5   número de interacción  5103 non-null   float64
 6   color presionado       5103 non-null   object 
 7   dificultad             5865 non-null   object 
 8   fecha                  5865 non-null   object 
 9   Juego                  5865 non-null   object 
 10  auto push              5103 non-null   float64
 11  tiempo de lección      5688 non-null   float64
 12  tiempo de sesión       5259 non-null   float64
dtypes: float64(6), object(7)
memory usage: 595.8+ KB


## Limpieza de Nulos 

In [5]:
data_cuanti=data_sucio.select_dtypes(include=["float64","int64","float","int"])
data_cuali=data_sucio.select_dtypes(include=["object","datetime","category","datetime64[ns]"])
data_cuali.info()
data_cuanti.info(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5865 entries, 0 to 5864
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Administrador     5865 non-null   object
 1   Usuario           5865 non-null   object
 2   mini juego        5709 non-null   object
 3   color presionado  5103 non-null   object
 4   dificultad        5865 non-null   object
 5   fecha             5865 non-null   object
 6   Juego             5865 non-null   object
dtypes: object(7)
memory usage: 320.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5865 entries, 0 to 5864
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   botón correcto         5103 non-null   float64
 1   tiempo de interacción  5103 non-null   float64
 2   número de interacción  5103 non-null   float64
 3   auto push              5103 non-null   float64
 4   tiempo de lecci

In [6]:
cualis_bfill=data_cuali.fillna(method="bfill")
cualis_ffill=data_cuali.fillna(method="ffill")
cuantias_mean=data_cuanti.fillna(round(data_cuanti.mean(),1))

data_sin_nulos = pd.concat([cuantias_mean,cualis_ffill],axis=1)

data_sin_nulos.head(5)

/var/folders/cr/23ck8vtn1kd8mbhg9wssxh440000gn/T/ipykernel_2271/3586926086.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  cualis_bfill=data_cuali.fillna(method="bfill")
/var/folders/cr/23ck8vtn1kd8mbhg9wssxh440000gn/T/ipykernel_2271/3586926086.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  cualis_ffill=data_cuali.fillna(method="ffill")


botón correcto  tiempo de interacción  número de interacción  auto push  \
0             1.0               5.399169                    1.0        0.0   
1             0.0               1.283400                    2.0        0.0   
2             1.0               2.700226                    3.0        0.0   
3             0.0               3.050262                    4.0        0.0   
4             0.0               4.750256                    5.0        0.0   

   tiempo de lección  tiempo de sesión Administrador  Usuario mini juego  \
0                0.0               0.0       nicolas  nicolas   Despegue   
1                0.0               0.0       nicolas  nicolas   Despegue   
2                0.0               0.0       nicolas  nicolas   Despegue   
3                0.0               0.0       nicolas  nicolas   Despegue   
4                0.0               0.0       nicolas  nicolas   Despegue   

  color presionado  dificultad                      fecha  Juego  
0             blue  Episodio 1  25/01/2024 09:26:42 a. m.  Astro  
1           violet  Episodio 1  25/01/2024 09:26:46 a. m.  Astro  
2            green  Episodio 1  25/01/2024 09:26:48 a. m.  Astro  
3            green  Episodio 1  25/01/2024 09:26:57 a. m.  Astro  
4            green  Episodio 1  25/01/2024 09:26:58 a. m.  Astro

In [7]:
data=data_sin_nulos.isnull().sum().sum()
print(data)

0


In [8]:
DATA = data

## Limpieza Outliers

In [9]:
cuantitativas=data_sucio.select_dtypes(include=["float64","int64","float","int"])
cualitativas=data_sucio.select_dtypes(include=["object","datetime","category"])
y=cuantitativas

percentile25=y.quantile(0.25)
percentile75=y.quantile(0.75)
iqr= percentile75-percentile25

Limite_Superior_iqr= percentile75+1.5*iqr
Limite_Inferior_iqr= percentile25-1.5*iqr
iqr=cuantitativas[(y<=Limite_Superior_iqr)&y>=(Limite_Inferior_iqr)]
iqr2=iqr.fillna(round(iqr.mean(),1))
rango_intercuartilico=pd.concat([cualitativas,iqr2],axis=1)
rango_intercuartilico.head(5)

Administrador  Usuario mini juego color presionado  dificultad  \
0       nicolas  nicolas   Despegue             blue  Episodio 1   
1       nicolas  nicolas   Despegue           violet  Episodio 1   
2       nicolas  nicolas   Despegue            green  Episodio 1   
3       nicolas  nicolas   Despegue            green  Episodio 1   
4       nicolas  nicolas   Despegue            green  Episodio 1   

                       fecha  Juego  botón correcto  tiempo de interacción  \
0  25/01/2024 09:26:42 a. m.  Astro             1.0               5.399169   
1  25/01/2024 09:26:46 a. m.  Astro             0.0               1.283400   
2  25/01/2024 09:26:48 a. m.  Astro             1.0               2.700226   
3  25/01/2024 09:26:57 a. m.  Astro             0.0               3.050262   
4  25/01/2024 09:26:58 a. m.  Astro             0.0               4.750256   

   número de interacción  auto push  tiempo de lección  tiempo de sesión  
0                    1.0        0.0                0.0               0.0  
1                    2.0        0.0                0.0               0.0  
2                    3.0        0.0                0.0               0.0  
3                    4.0        0.0                0.0               0.0  
4                    5.0        0.0                0.0               0.0

In [10]:
cualis_bfill=data_cuali.fillna(method="bfill")
cualis_ffill=data_cuali.fillna(method="ffill")
cuantias_mean=data_cuanti.fillna(round(data_cuanti.mean(),1))

data = pd.concat([cuantias_mean,cualis_ffill],axis=1)

data.head(5)

/var/folders/cr/23ck8vtn1kd8mbhg9wssxh440000gn/T/ipykernel_2271/3308866133.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  cualis_bfill=data_cuali.fillna(method="bfill")
/var/folders/cr/23ck8vtn1kd8mbhg9wssxh440000gn/T/ipykernel_2271/3308866133.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  cualis_ffill=data_cuali.fillna(method="ffill")


botón correcto  tiempo de interacción  número de interacción  auto push  \
0             1.0               5.399169                    1.0        0.0   
1             0.0               1.283400                    2.0        0.0   
2             1.0               2.700226                    3.0        0.0   
3             0.0               3.050262                    4.0        0.0   
4             0.0               4.750256                    5.0        0.0   

   tiempo de lección  tiempo de sesión Administrador  Usuario mini juego  \
0                0.0               0.0       nicolas  nicolas   Despegue   
1                0.0               0.0       nicolas  nicolas   Despegue   
2                0.0               0.0       nicolas  nicolas   Despegue   
3                0.0               0.0       nicolas  nicolas   Despegue   
4                0.0               0.0       nicolas  nicolas   Despegue   

  color presionado  dificultad                      fecha  Juego  
0             blue  Episodio 1  25/01/2024 09:26:42 a. m.  Astro  
1           violet  Episodio 1  25/01/2024 09:26:46 a. m.  Astro  
2            green  Episodio 1  25/01/2024 09:26:48 a. m.  Astro  
3            green  Episodio 1  25/01/2024 09:26:57 a. m.  Astro  
4            green  Episodio 1  25/01/2024 09:26:58 a. m.  Astro

In [11]:
outliers_limpios=data.isnull().sum().sum()
print(outliers_limpios)

0


## Analizar la correlación logística (botón correcto, juego, auto push)

In [12]:
df = pd.read_csv('DataAnalytics.csv')
df.head()

Administrador  Usuario  botón correcto  tiempo de interacción mini juego  \
0       nicolas  nicolas             1.0               5.399169   Despegue   
1       nicolas  nicolas             0.0               1.283400   Despegue   
2       nicolas  nicolas             1.0               2.700226   Despegue   
3       nicolas  nicolas             0.0               3.050262   Despegue   
4       nicolas  nicolas             0.0               4.750256   Despegue   

   número de interacción color presionado  dificultad  \
0                    1.0             blue  Episodio 1   
1                    2.0           violet  Episodio 1   
2                    3.0            green  Episodio 1   
3                    4.0            green  Episodio 1   
4                    5.0            green  Episodio 1   

                       fecha  Juego  auto push  tiempo de lección  \
0  25/01/2024 09:26:42 a. m.  Astro        0.0                0.0   
1  25/01/2024 09:26:46 a. m.  Astro        0.0                0.0   
2  25/01/2024 09:26:48 a. m.  Astro        0.0                0.0   
3  25/01/2024 09:26:57 a. m.  Astro        0.0                0.0   
4  25/01/2024 09:26:58 a. m.  Astro        0.0                0.0   

   tiempo de sesión  
0               0.0  
1               0.0  
2               0.0  
3               0.0  
4               0.0

In [13]:
# Crear un diccionario para almacenar los modelos de regresión logística
logistic_models = {}

In [14]:
# Preparamos los datos, eliminando nulos y codificando 'Juego'
df_clean = df[['botón correcto', 'auto push', 'Juego', 'número de interacción', 'tiempo de interacción']].dropna()

In [15]:
# Convertir 'Juego' en variable binaria para regresión logística (0 si es el juego más común, 1 si no)
juego_mas_comun = df_clean['Juego'].mode()[0]
df_clean['Juego_binaria'] = (df_clean['Juego'] != juego_mas_comun).astype(int)

In [16]:
df_clean['Juego_binaria']

0       0
1       0
2       0
3       0
4       0
       ..
5854    0
5855    0
5856    0
5857    0
5861    0
Name: Juego_binaria, Length: 5103, dtype: int64

In [17]:
df_clean.head()

botón correcto  auto push  Juego  número de interacción  \
0             1.0        0.0  Astro                    1.0   
1             0.0        0.0  Astro                    2.0   
2             1.0        0.0  Astro                    3.0   
3             0.0        0.0  Astro                    4.0   
4             0.0        0.0  Astro                    5.0   

   tiempo de interacción  Juego_binaria  
0               5.399169              0  
1               1.283400              0  
2               2.700226              0  
3               3.050262              0  
4               4.750256              0

In [18]:
Var_Indepx= df_clean[['número de interacción', 'tiempo de interacción']]
Var_Depy1=df_clean['botón correcto']
Var_Depy2=df_clean['auto push']
Var_Depy3=df_clean['Juego_binaria']

In [19]:
#Redefinimos las variables 
X= Var_Indepx
y1= Var_Depy1
y2= Var_Depy2
y3= Var_Depy3

In [20]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y1, test_size=0.3, random_state =None)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y1, test_size=0.3, random_state =None)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X, y1, test_size=0.3, random_state =None)

In [21]:
#Se escalan todos los datos
escalar = StandardScaler()

In [22]:
#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train1 = escalar.fit_transform(X_train1)
X_test1 = escalar.transform(X_test1)

X_train2 = escalar.fit_transform(X_train2)
X_test2 = escalar.transform(X_test2)

X_train3 = escalar.fit_transform(X_train3)
X_test3 = escalar.transform(X_test3)

In [23]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [24]:
#Entrenamos el modelo
algoritmo.fit(X_train1, y_train1)
algoritmo.fit(X_train2, y_train2)
algoritmo.fit(X_train3, y_train3)

LogisticRegression()

In [25]:
#Realizamos una predicción
y_pred1 = algoritmo.predict(X_test1) 
y_pred1

y_pred2 = algoritmo.predict(X_test2) 
y_pred2

y_pred3 = algoritmo.predict(X_test3) 
y_pred3

array([1., 1., 0., ..., 1., 1., 1.])

In [26]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz1 = confusion_matrix(y_test1, y_pred1)
print('Matriz de Confusión 1: ')
print(matriz1)

matriz2 = confusion_matrix(y_test2, y_pred2)
print('Matriz de Confusión 2: ')
print(matriz2)

matriz3 = confusion_matrix(y_test3, y_pred3)
print('Matriz de Confusión 3: ')
print(matriz3)

Matriz de Confusión 1: 
[[381 410]
 [120 620]]
Matriz de Confusión 2: 
[[389 386]
 [119 637]]
Matriz de Confusión 3: 
[[376 417]
 [105 633]]


In [27]:
# Modelo 1: botón correcto ~ número de interacción + tiempo de interacción
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

print("Modelo 1: Botón Correcto 0.0")
precision1_0= precision_score (y_test1, y_pred1, average="binary", pos_label=0.0)
print('Precisión del modelo: ',precision1_0 )
exactitud1_0 = accuracy_score(y_test1, y_pred1)
print('Exactitud del modelo: ', exactitud1_0)
sensibilidad1_0 = recall_score(y_test1, y_pred1, average="binary", pos_label=0.0)
print('Sensibilidad del modelo: ', sensibilidad1_0)
puntajef1_1_0 = f1_score(y_test1, y_pred1, average="binary", pos_label=0.0)
print('Puntaje F1 del modelo: ', puntajef1_1_0)
print("\n")

print("Modelo 1: Botón correcto 1.0 ")
precision1= precision_score (y_test1, y_pred1, average="binary", pos_label=1.0)
print('Precisión del modelo: ',precision1 )
exactitud1 = accuracy_score(y_test1, y_pred1)
print('Exactitud del modelo: ', exactitud1)
sensibilidad1 = recall_score(y_test1, y_pred1, average="binary", pos_label=1.0)
print('Sensibilidad del modelo: ', sensibilidad1)
puntajef1_1 = f1_score(y_test1, y_pred1, average="binary", pos_label=1.0)
print('Puntaje F1 del modelo: ', puntajef1_1)

Modelo 1: Botón Correcto 0.0
Precisión del modelo:  0.7604790419161677
Exactitud del modelo:  0.6538210320052253
Sensibilidad del modelo:  0.48166877370417194
Puntaje F1 del modelo:  0.5897832817337462


Modelo 1: Botón correcto 1.0 
Precisión del modelo:  0.6019417475728155
Exactitud del modelo:  0.6538210320052253
Sensibilidad del modelo:  0.8378378378378378
Puntaje F1 del modelo:  0.7005649717514124


In [28]:
# Modelo 2: Auto Push ~ número de interacción + tiempo de interacción
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

print("Modelo 2: Auto push 0.0")
precision2_0= precision_score (y_test2, y_pred2, average="binary", pos_label=0.0)
print('Precisión del modelo: ',precision2_0 )
exactitud2_0 = accuracy_score(y_test2, y_pred2)
print('Exactitud del modelo: ', exactitud2_0)
sensibilidad2_0 = recall_score(y_test2, y_pred2, average="binary", pos_label=0.0)
print('Sensibilidad del modelo: ', sensibilidad2_0)
puntajef1_2_0 = f1_score(y_test2, y_pred2, average="binary", pos_label=0.0)
print('Puntaje F1 del modelo: ', puntajef1_2_0)
print("\n")


print("Modelo 2: Auto push 1.0")
precision2= precision_score (y_test2, y_pred2, average="binary", pos_label=1.0)
print('Precisión del modelo: ',precision2 )
exactitud2 = accuracy_score(y_test2, y_pred2)
print('Exactitud del modelo: ', exactitud2)
sensibilidad2 = recall_score(y_test2, y_pred2, average="binary", pos_label=1.0)
print('Sensibilidad del modelo: ', sensibilidad2)
puntajef1_2 = f1_score(y_test2, y_pred2, average="binary", pos_label=1.0)
print('Puntaje F1 del modelo: ', puntajef1_2)

Modelo 2: Auto push 0.0
Precisión del modelo:  0.765748031496063
Exactitud del modelo:  0.6701502286087524
Sensibilidad del modelo:  0.5019354838709678
Puntaje F1 del modelo:  0.6063912704598597


Modelo 2: Auto push 1.0
Precisión del modelo:  0.6226783968719453
Exactitud del modelo:  0.6701502286087524
Sensibilidad del modelo:  0.8425925925925926
Puntaje F1 del modelo:  0.716132658797077


In [29]:
# Modelo 3: Juego ~ número de interacción + tiempo de interacción
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

print("Modelo 3: Juego 0.0")
precision3_0= precision_score (y_test3, y_pred3, average="binary", pos_label=0.0)
print('Precisión del modelo: ',precision3_0 )
exactitud3_0 = accuracy_score(y_test3, y_pred3)
print('Exactitud del modelo: ', exactitud3_0)
sensibilidad3_0 = recall_score(y_test3, y_pred3, average="binary", pos_label=0.0)
print('Sensibilidad del modelo: ', sensibilidad3_0)
puntajef1_3_0 = f1_score(y_test1, y_pred1, average="binary", pos_label=0.0)
print('Puntaje F1 del modelo: ', puntajef1_3_0)
print("\n")

print("Modelo 3: Juego 1.0")
precision3= precision_score (y_test3, y_pred3, average="binary", pos_label=1.0)
print('Precisión del modelo: ',precision3 )
exactitud3 = accuracy_score(y_test3, y_pred3)
print('Exactitud del modelo: ', exactitud3)
sensibilidad3 = recall_score(y_test3, y_pred3, average="binary", pos_label=1.0)
print('Sensibilidad del modelo: ', sensibilidad3)
puntajef1_3 = f1_score(y_test1, y_pred1, average="binary", pos_label=1.0)
print('Puntaje F1 del modelo: ', puntajef1_3)

Modelo 3: Juego 0.0
Precisión del modelo:  0.7817047817047817
Exactitud del modelo:  0.659046374918354
Sensibilidad del modelo:  0.47414880201765447
Puntaje F1 del modelo:  0.5897832817337462


Modelo 3: Juego 1.0
Precisión del modelo:  0.6028571428571429
Exactitud del modelo:  0.659046374918354
Sensibilidad del modelo:  0.8577235772357723
Puntaje F1 del modelo:  0.7005649717514124


## Convertir las variables en tipo dicotómica y analizarlas

Función de Regresión Logística

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

def regresioncion_logistica(dicotomica,si,no):
    dicotomica=dicotomica.replace(si,"0")
    dicotomica=dicotomica.replace(no,"1")
    dicotomica = dicotomica.apply(pd.to_numeric, errors="coerce")
    Var_Indepx= data[['número de interacción', 'tiempo de interacción']]
    Var_Depy=dicotomica
    X= Var_Indepx
    Y= Var_Depy
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state =None)
    escalar = StandardScaler()
    X_train = escalar.fit_transform(X_train)
    X_test = escalar.transform(X_test)
    algoritmo = LogisticRegression()
    algoritmo.fit(X_train, Y_train)
    Y_pred = algoritmo.predict(X_test) 
    matriz = confusion_matrix(Y_test, Y_pred)
    print('Matriz de Confusión: ')
    print(matriz)
    print("Modelo 0:")
    precision0= precision_score (Y_test, Y_pred, average="binary", pos_label=0.0)
    print('Precisión del modelo: ',precision0 )
    exactitud0 = accuracy_score(Y_test, Y_pred)
    print('Exactitud del modelo: ', exactitud0)
    sensibilidad0 = recall_score(Y_test, Y_pred, average="binary", pos_label=0.0)
    print('Sensibilidad del modelo: ', sensibilidad0)
    puntajef0 = f1_score(Y_test, Y_pred, average="binary", pos_label=0.0)
    print('Puntaje F1 del modelo: ', puntajef0)
    print("\n")
    print("Modelo 1:")
    precision1= precision_score (Y_test, Y_pred, average="binary", pos_label=1.0)
    print('Precisión del modelo: ',precision1 )
    exactitud1 = accuracy_score(Y_test, Y_pred)
    print('Exactitud del modelo: ', exactitud1)
    sensibilidad1 = recall_score(Y_test, Y_pred, average="binary", pos_label=1.0)
    print('Sensibilidad del modelo: ', sensibilidad1)
    puntajef1_1 = f1_score(Y_test, Y_pred, average="binary", pos_label=1.0)
    print('Puntaje F1 del modelo: ', puntajef1_1)

Color Presionado (5)

In [31]:
copr = np.unique(data_sin_nulos['color presionado'])
copr

array(['blue', 'green', 'red', 'violet', 'yellow'], dtype=object)

In [32]:
blue= data_sin_nulos['color presionado'].replace(["green", "red", "violet", "yellow"], "no blue")
blue

0          blue
1       no blue
2       no blue
3       no blue
4       no blue
         ...   
5860    no blue
5861    no blue
5862    no blue
5863    no blue
5864    no blue
Name: color presionado, Length: 5865, dtype: object

In [33]:
blue_relo=regresioncion_logistica(blue,"blue","no blue")

Matriz de Confusión: 
[[   0  405]
 [   0 1355]]
Modelo 0:
Precisión del modelo:  0.0
Exactitud del modelo:  0.7698863636363636
Sensibilidad del modelo:  0.0
Puntaje F1 del modelo:  0.0


Modelo 1:
Precisión del modelo:  0.7698863636363636
Exactitud del modelo:  0.7698863636363636
Sensibilidad del modelo:  1.0
Puntaje F1 del modelo:  0.869983948635634


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [34]:
green= data_sin_nulos['color presionado'].replace(["blue", "red", "violet", "yellow"], "no green")
green

0       no green
1       no green
2          green
3          green
4          green
          ...   
5860       green
5861       green
5862       green
5863       green
5864       green
Name: color presionado, Length: 5865, dtype: object

In [35]:
green_relo=regresioncion_logistica(green,"green","no green")

Matriz de Confusión: 
[[   0  427]
 [   0 1333]]
Modelo 0:
Precisión del modelo:  0.0
Exactitud del modelo:  0.7573863636363637
Sensibilidad del modelo:  0.0
Puntaje F1 del modelo:  0.0


Modelo 1:
Precisión del modelo:  0.7573863636363637
Exactitud del modelo:  0.7573863636363637
Sensibilidad del modelo:  1.0
Puntaje F1 del modelo:  0.861946330423537


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [36]:
red= data_sin_nulos['color presionado'].replace(["blue", "green", "violet", "yellow"], "no red")
red

0       no red
1       no red
2       no red
3       no red
4       no red
         ...  
5860    no red
5861    no red
5862    no red
5863    no red
5864    no red
Name: color presionado, Length: 5865, dtype: object

In [37]:
red_relo=regresioncion_logistica(red,"red","no red")

Matriz de Confusión: 
[[   0   10]
 [   0 1750]]
Modelo 0:
Precisión del modelo:  0.0
Exactitud del modelo:  0.9943181818181818
Sensibilidad del modelo:  0.0
Puntaje F1 del modelo:  0.0


Modelo 1:
Precisión del modelo:  0.9943181818181818
Exactitud del modelo:  0.9943181818181818
Sensibilidad del modelo:  1.0
Puntaje F1 del modelo:  0.9971509971509972


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [38]:
violet= data_sin_nulos['color presionado'].replace(["blue", "green", "red", "yellow"], "no violet")
violet

0       no violet
1          violet
2       no violet
3       no violet
4       no violet
          ...    
5860    no violet
5861    no violet
5862    no violet
5863    no violet
5864    no violet
Name: color presionado, Length: 5865, dtype: object

In [39]:
violet_relo=regresioncion_logistica(violet,"violet","no violet")

Matriz de Confusión: 
[[  52  405]
 [   4 1299]]
Modelo 0:
Precisión del modelo:  0.9285714285714286
Exactitud del modelo:  0.7676136363636363
Sensibilidad del modelo:  0.1137855579868709
Puntaje F1 del modelo:  0.20272904483430798


Modelo 1:
Precisión del modelo:  0.7623239436619719
Exactitud del modelo:  0.7676136363636363
Sensibilidad del modelo:  0.9969301611665388
Puntaje F1 del modelo:  0.863984037246425


In [40]:
yellow= data_sin_nulos['color presionado'].replace(["blue", "green", "red", "violet"], "no yellow")
yellow

0       no yellow
1       no yellow
2       no yellow
3       no yellow
4       no yellow
          ...    
5860    no yellow
5861    no yellow
5862    no yellow
5863    no yellow
5864    no yellow
Name: color presionado, Length: 5865, dtype: object

In [41]:
yellow_relo=regresioncion_logistica(yellow,"yellow","no yellow")

Matriz de Confusión: 
[[   0  413]
 [   0 1347]]
Modelo 0:
Precisión del modelo:  0.0
Exactitud del modelo:  0.7653409090909091
Sensibilidad del modelo:  0.0
Puntaje F1 del modelo:  0.0


Modelo 1:
Precisión del modelo:  0.7653409090909091
Exactitud del modelo:  0.7653409090909091
Sensibilidad del modelo:  1.0
Puntaje F1 del modelo:  0.8670743482458964


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Dificultad

In [42]:
dif = np.unique(data_sin_nulos['dificultad'])
dif

array(['Episodio 1', 'Episodio 2', 'Episodio 3', 'Episodio 4'],
      dtype=object)

In [43]:
E1= data_sin_nulos['dificultad'].replace(["Episodio 2", "Episodio 3", "Episodio 4"], "NO Episodio 1")
E1

0          Episodio 1
1          Episodio 1
2          Episodio 1
3          Episodio 1
4          Episodio 1
            ...      
5860       Episodio 1
5861    NO Episodio 1
5862    NO Episodio 1
5863    NO Episodio 1
5864    NO Episodio 1
Name: dificultad, Length: 5865, dtype: object

In [44]:
E1_relo=regresioncion_logistica(E1,"Episodio 1","NO Episodio 1")

Matriz de Confusión: 
[[ 101  599]
 [  47 1013]]
Modelo 0:
Precisión del modelo:  0.6824324324324325
Exactitud del modelo:  0.6329545454545454
Sensibilidad del modelo:  0.1442857142857143
Puntaje F1 del modelo:  0.23820754716981132


Modelo 1:
Precisión del modelo:  0.6284119106699751
Exactitud del modelo:  0.6329545454545454
Sensibilidad del modelo:  0.9556603773584905
Puntaje F1 del modelo:  0.7582335329341318


In [45]:
E2= data_sin_nulos['dificultad'].replace(["Episodio 1", "Episodio 3", "Episodio 4"], "NO Episodio 2")
E2

0       NO Episodio 2
1       NO Episodio 2
2       NO Episodio 2
3       NO Episodio 2
4       NO Episodio 2
            ...      
5860    NO Episodio 2
5861    NO Episodio 2
5862    NO Episodio 2
5863    NO Episodio 2
5864    NO Episodio 2
Name: dificultad, Length: 5865, dtype: object

In [46]:
E2_relo=regresioncion_logistica(E2,"Episodio 2","NO Episodio 2")

Matriz de Confusión: 
[[   0  445]
 [   0 1315]]
Modelo 0:
Precisión del modelo:  0.0
Exactitud del modelo:  0.7471590909090909
Sensibilidad del modelo:  0.0
Puntaje F1 del modelo:  0.0


Modelo 1:
Precisión del modelo:  0.7471590909090909
Exactitud del modelo:  0.7471590909090909
Sensibilidad del modelo:  1.0
Puntaje F1 del modelo:  0.8552845528455284


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [47]:
E3= data_sin_nulos['dificultad'].replace(["Episodio 1", "Episodio 2", "Episodio 4"], "NO Episodio 3")
E3

0       NO Episodio 3
1       NO Episodio 3
2       NO Episodio 3
3       NO Episodio 3
4       NO Episodio 3
            ...      
5860    NO Episodio 3
5861       Episodio 3
5862       Episodio 3
5863       Episodio 3
5864       Episodio 3
Name: dificultad, Length: 5865, dtype: object

In [48]:
E3_relo=regresioncion_logistica(E3,"Episodio 3","NO Episodio 3")

Matriz de Confusión: 
[[   0  385]
 [   3 1372]]
Modelo 0:
Precisión del modelo:  0.0
Exactitud del modelo:  0.7795454545454545
Sensibilidad del modelo:  0.0
Puntaje F1 del modelo:  0.0


Modelo 1:
Precisión del modelo:  0.7808764940239044
Exactitud del modelo:  0.7795454545454545
Sensibilidad del modelo:  0.9978181818181818
Puntaje F1 del modelo:  0.876117496807152


In [49]:
E4= data_sin_nulos['dificultad'].replace(["Episodio 1", "Episodio 2", "Episodio 3"], "NO Episodio 4")
E4

0       NO Episodio 4
1       NO Episodio 4
2       NO Episodio 4
3       NO Episodio 4
4       NO Episodio 4
            ...      
5860    NO Episodio 4
5861    NO Episodio 4
5862    NO Episodio 4
5863    NO Episodio 4
5864    NO Episodio 4
Name: dificultad, Length: 5865, dtype: object

In [50]:
E4_relo=regresioncion_logistica(E4,"Episodio 4","NO Episodio 4")

Matriz de Confusión: 
[[   0  218]
 [   0 1542]]
Modelo 0:
Precisión del modelo:  0.0
Exactitud del modelo:  0.8761363636363636
Sensibilidad del modelo:  0.0
Puntaje F1 del modelo:  0.0


Modelo 1:
Precisión del modelo:  0.8761363636363636
Exactitud del modelo:  0.8761363636363636
Sensibilidad del modelo:  1.0
Puntaje F1 del modelo:  0.9339794064203513


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Mini Juego(2)

In [51]:
#numero de interacción, usuario(5))
miju = np.unique(data_sin_nulos['mini juego'])
miju

array(['Asteroides', 'Despegue', 'Estrellas', 'Gusanos', 'MiniGame_0',
       'MiniGame_1', 'MiniGame_2', 'MiniGame_3', 'Restaurante',
       'animales y colores', 'figuras y colores', 'partes del cuerpo',
       'sonidos y animales'], dtype=object)

In [52]:
Asteroides= data_sin_nulos['mini juego'].replace(["Despegue", "Estrellas", "Gusanos", "MiniGame_0", "MiniGame_1", "MiniGame_2", "MiniGame_3", "Restaurante", "animales y colores", "figuras y colores", "partes del cuerpo", "sonidos y animales"], "NO Asteroides")
Asteroides

0       NO Asteroides
1       NO Asteroides
2       NO Asteroides
3       NO Asteroides
4       NO Asteroides
            ...      
5860    NO Asteroides
5861       Asteroides
5862       Asteroides
5863       Asteroides
5864    NO Asteroides
Name: mini juego, Length: 5865, dtype: object

In [53]:
Asteroides_relo=regresioncion_logistica(Asteroides,"Asteroides","NO Asteroides")

Matriz de Confusión: 
[[   0  315]
 [   1 1444]]
Modelo 0:
Precisión del modelo:  0.0
Exactitud del modelo:  0.8204545454545454
Sensibilidad del modelo:  0.0
Puntaje F1 del modelo:  0.0


Modelo 1:
Precisión del modelo:  0.8209209778283115
Exactitud del modelo:  0.8204545454545454
Sensibilidad del modelo:  0.9993079584775086
Puntaje F1 del modelo:  0.9013732833957553


In [54]:
Despegue= data_sin_nulos['mini juego'].replace(["Asteroides", "Estrellas", "Gusanos", "MiniGame_0", "MiniGame_1", "MiniGame_2", "MiniGame_3", "Restaurante", "animales y colores", "figuras y colores", "partes del cuerpo", "sonidos y animales"], "NO Despegue")
Despegue

0          Despegue
1          Despegue
2          Despegue
3          Despegue
4          Despegue
           ...     
5860    NO Despegue
5861    NO Despegue
5862    NO Despegue
5863    NO Despegue
5864    NO Despegue
Name: mini juego, Length: 5865, dtype: object

In [55]:
Despegue_relo=regresioncion_logistica(Despegue,"Despegue","NO Despegue")

Matriz de Confusión: 
[[   0   51]
 [   0 1709]]
Modelo 0:
Precisión del modelo:  0.0
Exactitud del modelo:  0.9710227272727273
Sensibilidad del modelo:  0.0
Puntaje F1 del modelo:  0.0


Modelo 1:
Precisión del modelo:  0.9710227272727273
Exactitud del modelo:  0.9710227272727273
Sensibilidad del modelo:  1.0
Puntaje F1 del modelo:  0.9852983568751802


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Numero de Interacción

In [56]:
Max=data_sin_nulos['número de interacción'].max()
Min=data_sin_nulos['número de interacción'].min()
Limites= [Min, Max]
Limites

[1.0, 256.0]

In [57]:
intervalos=np.linspace(0.9, 256.1, 3)
print(intervalos)
categorias= ["Interacción Baja", "Interacción Alta"]

[  0.9 128.5 256.1]


In [58]:
pd.options.display.max_rows = None

In [59]:
internew=pd.cut(x= data_sin_nulos['número de interacción'], bins=intervalos, labels= categorias )
internew.head()

0    Interacción Baja
1    Interacción Baja
2    Interacción Baja
3    Interacción Baja
4    Interacción Baja
Name: número de interacción, dtype: category
Categories (2, object): ['Interacción Baja' < 'Interacción Alta']

In [60]:
internew_relo=regresioncion_logistica(internew,"Interacción Alta","Interacción Baja")

Matriz de Confusión: 
[[  39    0]
 [   3 1718]]
Modelo 0:
Precisión del modelo:  0.9285714285714286
Exactitud del modelo:  0.9982954545454545
Sensibilidad del modelo:  1.0
Puntaje F1 del modelo:  0.9629629629629629


Modelo 1:
Precisión del modelo:  1.0
Exactitud del modelo:  0.9982954545454545
Sensibilidad del modelo:  0.9982568274259151
Puntaje F1 del modelo:  0.9991276533876127


/var/folders/cr/23ck8vtn1kd8mbhg9wssxh440000gn/T/ipykernel_2271/521905368.py:9: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  dicotomica=dicotomica.replace(si,"0")
/var/folders/cr/23ck8vtn1kd8mbhg9wssxh440000gn/T/ipykernel_2271/521905368.py:10: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  dicotomica=dicotomica.replace(no,"1")


In [61]:
data = data_sin_nulos.copy()

Usuario (5)

In [62]:
us = np.unique(data_sin_nulos['Usuario'])
us

array(['ADRIAN ', 'ALEIDA', 'ARLETT', 'ASHLEY ', 'AUSTIN', 'BENJAMIN',
       'CARLOS ABEL', 'CARLOS ENRIQUE', 'CONCEPCION', 'DENISSE',
       'ERICK OSVALDO', 'ESMERALDA', 'IKER BENJAMIN', 'INGRID', 'IRVING ',
       'JESUS ALEJANDRO', 'JOSE IAN', 'JOSE IGNACIO TADEO',
       'JOSE JAVIER ', 'JOSHUA', 'KYTZIA', 'LEONARDO', 'LEONARDO ',
       'MA DEL ROSARIO ', 'NICOLAS |', 'RENE ', 'SERGIO ANGEL',
       'VALENTIN', 'YAEL DAVID', 'YEREMI YAZMIN ', 'erick ',
       'jesus eduardo', 'nicolas', 'ramiro isai'], dtype=object)

In [63]:
ADRIAN= data_sin_nulos['Usuario'].replace(['ALEIDA', 'ARLETT', 'ASHLEY ', 'AUSTIN', 'BENJAMIN','CARLOS ABEL', 'CARLOS ENRIQUE', 'CONCEPCION', 'DENISSE','ERICK OSVALDO', 'ESMERALDA', 'IKER BENJAMIN', 'INGRID', 'IRVING ','JESUS ALEJANDRO', 'JOSE IAN', 'JOSE IGNACIO TADEO','JOSE JAVIER ', 'JOSHUA', 'KYTZIA', 'LEONARDO', 'LEONARDO ','MA DEL ROSARIO ', 'NICOLAS |', 'RENE ', 'SERGIO ANGEL','VALENTIN', 'YAEL DAVID', 'YEREMI YAZMIN ', 'erick ','jesus eduardo', 'nicolas', 'ramiro isai'], "NO ADRIAN")
ADRIAN.head()

0    NO ADRIAN
1    NO ADRIAN
2    NO ADRIAN
3    NO ADRIAN
4    NO ADRIAN
Name: Usuario, dtype: object

In [64]:
ADRIAN_relo=regresioncion_logistica(ADRIAN,"ADRIAN","NO ADRIAN")

ValueError: Input y contains NaN.

In [65]:
ALEIDA= data_sin_nulos['Usuario'].replace(['ADRIAN', 'ARLETT', 'ASHLEY ', 'AUSTIN', 'BENJAMIN','CARLOS ABEL', 'CARLOS ENRIQUE', 'CONCEPCION', 'DENISSE','ERICK OSVALDO', 'ESMERALDA', 'IKER BENJAMIN', 'INGRID', 'IRVING ','JESUS ALEJANDRO', 'JOSE IAN', 'JOSE IGNACIO TADEO','JOSE JAVIER ', 'JOSHUA', 'KYTZIA', 'LEONARDO', 'LEONARDO ','MA DEL ROSARIO ', 'NICOLAS |', 'RENE ', 'SERGIO ANGEL','VALENTIN', 'YAEL DAVID', 'YEREMI YAZMIN ', 'erick ','jesus eduardo', 'nicolas', 'ramiro isai'], "NO ALEIDA")
ALEIDA.head()

0    NO ALEIDA
1    NO ALEIDA
2    NO ALEIDA
3    NO ALEIDA
4    NO ALEIDA
Name: Usuario, dtype: object

In [66]:
ALEIDA_relo=regresioncion_logistica(ALEIDA,"ALEIDA","NO ALEIDA")

ValueError: Input y contains NaN.

In [67]:
ARLETT= data_sin_nulos['Usuario'].replace(['ADRIAN', 'ALEIDA', 'ASHLEY ', 'AUSTIN', 'BENJAMIN','CARLOS ABEL', 'CARLOS ENRIQUE', 'CONCEPCION', 'DENISSE','ERICK OSVALDO', 'ESMERALDA', 'IKER BENJAMIN', 'INGRID', 'IRVING ','JESUS ALEJANDRO', 'JOSE IAN', 'JOSE IGNACIO TADEO','JOSE JAVIER ', 'JOSHUA', 'KYTZIA', 'LEONARDO', 'LEONARDO ','MA DEL ROSARIO ', 'NICOLAS |', 'RENE ', 'SERGIO ANGEL','VALENTIN', 'YAEL DAVID', 'YEREMI YAZMIN ', 'erick ','jesus eduardo', 'nicolas', 'ramiro isai'], "NO ARLETT")
ARLETT.head()

0    NO ARLETT
1    NO ARLETT
2    NO ARLETT
3    NO ARLETT
4    NO ARLETT
Name: Usuario, dtype: object

In [68]:
ARLETT_relo=regresioncion_logistica(ARLETT,"ARLETT","NO ARLETT")

ValueError: Input y contains NaN.

In [69]:
ASHLEY= data_sin_nulos['Usuario'].replace(['ADRIAN', 'ALEIDA', 'ARLETT', 'AUSTIN', 'BENJAMIN','CARLOS ABEL', 'CARLOS ENRIQUE', 'CONCEPCION', 'DENISSE','ERICK OSVALDO', 'ESMERALDA', 'IKER BENJAMIN', 'INGRID', 'IRVING ','JESUS ALEJANDRO', 'JOSE IAN', 'JOSE IGNACIO TADEO','JOSE JAVIER ', 'JOSHUA', 'KYTZIA', 'LEONARDO', 'LEONARDO ','MA DEL ROSARIO ', 'NICOLAS |', 'RENE ', 'SERGIO ANGEL','VALENTIN', 'YAEL DAVID', 'YEREMI YAZMIN ', 'erick ','jesus eduardo', 'nicolas', 'ramiro isai'], "NO ASHLEY")
ASHLEY.head()

0    NO ASHLEY
1    NO ASHLEY
2    NO ASHLEY
3    NO ASHLEY
4    NO ASHLEY
Name: Usuario, dtype: object

In [70]:
ASHLEY_relo=regresioncion_logistica(ASHLEY,"ASHLEY","NO ASHLEY")

ValueError: Input y contains NaN.

In [71]:
AUSTIN= data_sin_nulos['Usuario'].replace(['ADRIAN', 'ALEIDA', 'ARLETT', 'ASHLEY ', 'BENJAMIN','CARLOS ABEL', 'CARLOS ENRIQUE', 'CONCEPCION', 'DENISSE','ERICK OSVALDO', 'ESMERALDA', 'IKER BENJAMIN', 'INGRID', 'IRVING ','JESUS ALEJANDRO', 'JOSE IAN', 'JOSE IGNACIO TADEO','JOSE JAVIER ', 'JOSHUA', 'KYTZIA', 'LEONARDO', 'LEONARDO ','MA DEL ROSARIO ', 'NICOLAS |', 'RENE ', 'SERGIO ANGEL','VALENTIN', 'YAEL DAVID', 'YEREMI YAZMIN ', 'erick ','jesus eduardo', 'nicolas', 'ramiro isai'], "NO AUSTIN")
AUSTIN.head()

0    NO AUSTIN
1    NO AUSTIN
2    NO AUSTIN
3    NO AUSTIN
4    NO AUSTIN
Name: Usuario, dtype: object

In [72]:
AUSTIN_relo=regresioncion_logistica(AUSTIN,"AUSTIN","NO AUSTIN")

ValueError: Input y contains NaN.

## Realizar una tabla de todos los coeficientes de precisión, exactitud y sensibilidad 

Botón correcto

In [73]:
tabla_metricas = pd.DataFrame({
    'Clase': ['Botón correcto 0.0', 'Botón correcto 1.0'],
    'Precisión': [precision1_0, precision1],
    'Exactitud': [exactitud1_0, exactitud1],
    'Sensibilidad (Recall)': [sensibilidad1_0, sensibilidad1],
    'Puntaje F1': [puntajef1_1_0, puntajef1_1]
})

# Mostrar tabla
print("Métricas de Botón Correcto: \n", tabla_metricas)

Métricas de Botón Correcto: 
                 Clase  Precisión  Exactitud  Sensibilidad (Recall)  Puntaje F1
0  Botón correcto 0.0   0.760479   0.653821               0.481669    0.589783
1  Botón correcto 1.0   0.601942   0.653821               0.837838    0.700565


Juego

In [74]:
tabla_metricas = pd.DataFrame({
    'Clase': ['Botón correcto 0.0', 'Botón correcto 1.0'],
    'Precisión': [precision2_0, precision2],
    'Exactitud': [exactitud2_0, exactitud2],
    'Sensibilidad (Recall)': [sensibilidad2_0, sensibilidad2],
    'Puntaje F1': [puntajef1_2_0, puntajef1_2]
})

# Mostrar tabla
print("Métricas de Juego: \n",tabla_metricas)

Métricas de Juego: 
                 Clase  Precisión  Exactitud  Sensibilidad (Recall)  Puntaje F1
0  Botón correcto 0.0   0.765748    0.67015               0.501935    0.606391
1  Botón correcto 1.0   0.622678    0.67015               0.842593    0.716133


Auto push

In [75]:
tabla_metricas = pd.DataFrame({
    'Clase': ['Botón correcto 0.0', 'Botón correcto 1.0'],
    'Precisión': [precision3_0, precision3],
    'Exactitud': [exactitud3_0, exactitud3],
    'Sensibilidad (Recall)': [sensibilidad3_0, sensibilidad3],
    'Puntaje F1': [puntajef1_3_0, puntajef1_3]
})

# Mostrar tabla
print("Métricas de Auto Push: \n",tabla_metricas)

Métricas de Auto Push: 
                 Clase  Precisión  Exactitud  Sensibilidad (Recall)  Puntaje F1
0  Botón correcto 0.0   0.781705   0.659046               0.474149    0.589783
1  Botón correcto 1.0   0.602857   0.659046               0.857724    0.700565
